#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'r-fxxk'

class muhothi < Brainfuck
  nxt "ウエエエエエエエエエエエアアアアアア！！！"
  inc "\( 'ω')/<ウオオオオオアアアーーーッ！！！"
  prv "！！！アアアアアアエエエエエエエエエエエウ"
  dec "\( 'ω')/<ウオオオオオアエアーアート！！！"
  opn "いや草に草を生やしてさらに草を飾って草アートを描きたいレベルで草"
  cls "菅さんに菅さんを生やしてさらに菅さんを飾って菅さんアートを描きたいレベルで菅さん"
  put "ああそうだねえええええええええええええ！！！"
  get "ウニャアアアアアアアアアアアアアアア！！！"
end

puts muhothi.new.fuck(ARGF.read)
